version: "3.8"

services:
  app:
    build: .
    container_name: esmerald_app
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://root:root@mongodb:27017
      - MONGO_DB=test_database
      - UPLOAD_DIR=/media/uploaded-files
      # - UPLOAD_DIR=/app/media/uploaded-files
      # - UPLOAD_DIR=/var/lib/playmity/media/uploaded-files
    volumes:
      - ./media/uploaded-files:/media/uploaded-files # Esmerald sees files here

    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./media/uploaded-files:/var/lib/playmity/media/uploaded-files # Nginx sees files here
    depends_on:
      - app
    restart: unless-stopped

  mongodb:
    image: mongodb/mongodb-community-server
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongo_db_data:/mongodb_data/db

volumes:
  mongo_db_data:
    driver: local
